import type { Metadata } from "next";
import { AppSidebar } from "@/components/AppSidebar";
import "./globals.css";
import { SessionProvider } from '@/hooks/use-session';
import { SessionGate } from '@/components/SessionGate';
import { Toaster } from '@/components/ui/sonner';

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`antialiased`}
      >
        <SessionProvider>
          <SessionGate>
            <div className="flex">
              <AppSidebar />
              <main className="flex-1">{children}</main>
            </div>
          </SessionGate>
        </SessionProvider>
        <Toaster position="top-right" richColors />
      </body>
    </html>
  );
}
